FROM node:20.17.0

ARG VITE_CLIENT_ID
ARG VITE_FRONT_URL
ARG VITE_API_URL
ARG VITE_SENLER_INTEGRATION_ID
ARG VITE_SENLER_DOMAIN

ENV VITE_CLIENT_ID ${VITE_CLIENT_ID}
ENV VITE_FRONT_URL ${VITE_FRONT_URL}
ENV VITE_API_URL ${VITE_API_URL}
ENV VITE_SENLER_INTEGRATION_ID ${VITE_SENLER_INTEGRATION_ID}
ENV VITE_SENLER_DOMAIN ${VITE_SENLER_DOMAIN}

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build -- --outDir=temp

RUN rm -rf /app/dist/*

CMD cp -r /app/temp/* /app/dist/
